# 以phusion/passenger-ruby22镜像为基础
FROM phusion/passenger-ruby22

# 设置时区
RUN echo "Asia/Shanghai" > /etc/timezone
RUN dpkg-reconfigure -f noninteractive tzdata

#设置当前环境变量
ENV HOME /root
#设置rails环境为生产环境
ENV RAILS_ENV production

CMD ["/sbin/my_init"]

# Gem源
RUN gem sources --add http://mirrors.aliyun.com/rubygems/ --remove https://rubygems.org/
RUN gem install bundler
RUN bundle config mirror.https://rubygems.org http://mirrors.aliyun.com/rubygems

# 缓存gem，如果Gemfil没有改变将不会从源直接下载
WORKDIR /tmp
ADD ./Gemfile Gemfile
ADD ./Gemfile.lock Gemfile.lock
RUN bundle install

# 启动nginx
# RUN rm -f /etc/service/nginx/down
# 配置nginx
# RUN rm /etc/nginx/sites-enabled/default
# ADD nginx.conf /etc/nginx/sites-enabled/webxx.conf

# 添加环境文件
# ADD nginx-env.conf /etc/nginx/main.d/nginx-env.conf

#增加Docker脚本
RUN mkdir -p /etc/my_init.d
ADD docker.sh /etc/my_init.d/docker.sh
RUN chmod +x /etc/my_init.d/docker.sh

# 项目目录
VOLUME ["/home/apps/webxx"]

# 将项目文件加入项目目录
# ADD . /home/apps/webxx

WORKDIR /home/apps/webxx
# 编译静态文件
RUN rake assets:precompile

# 清楚产生的缓存文件
RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
# 开放80端口
EXPOSE 80